language: python
python:
  - "3.6"
caceh:
    pip: True
env:
    global:
        - COVERALLS_PARALLEL=true
install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda init bash
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION coveralls
    - conda activate test-environment
    - conda env update -n test-environment -f environment.yml
    - pip install -e .
before_script:
    - "export MPLBACKEND=agg"

script:
  - pytest

after_success:
    - coveralls
